[global]
    workgroup = WORKGROUP
    server string = Parcel Test Server
    security = user

[Photos]
    path = /home/mudit/Pictures
    read only = No
    guest ok = Yes

[Robotics_Data]
    path = /home/mudit/Documents/ROS2_Logs
    read only = Yes